# Generated by Django 2.2 on 2019-04-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('party', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, upload_to='core/static/img')),
                ('slug', models.SlugField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='core/static/img')),
                ('fav_album', models.CharField(max_length=75)),
                ('fav_coffee', models.CharField(max_length=50)),
                ('fav_president', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, null=True)),
                ('followers', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('polarity', models.DecimalField(decimal_places=9, max_digits=10)),
                ('subjectivity', models.DecimalField(decimal_places=9, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('sentiment', models.DecimalField(decimal_places=9, max_digits=10)),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('tweet_id', models.CharField(max_length=100)),
                ('retweeted_id', models.CharField(max_length=100, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateMeanSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_sentiment', models.DecimalField(decimal_places=9, max_digits=10)),
                ('total_favorites', models.PositiveIntegerField(default=0)),
                ('total_retweets', models.PositiveIntegerField(default=0)),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
            ],
        ),
    ]
