# Generated by Django 2.2 on 2019-04-19 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=32, null=True)),
                ('lastName', models.CharField(max_length=32)),
                ('party', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='core/static/img')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, null=True)),
                ('followers', models.PositiveIntegerField(null=True)),
                ('id_str', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polarity', models.DecimalField(decimal_places=9, max_digits=10)),
                ('subjectivity', models.DecimalField(decimal_places=9, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePolarityAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivePolarityAverage', models.DecimalField(decimal_places=9, max_digits=10)),
                ('negativePolarityAverage', models.DecimalField(decimal_places=9, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
            ],
        ),
    ]
