# Generated by Django 2.2 on 2019-04-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'candidate-csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemeansentiment',
            options={'ordering': ['to_date_time']},
        ),
    ]
