# Generated by Django 2.2 on 2019-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemeansentiment',
            name='negative_engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatemeansentiment',
            name='negative_mean_sentiment',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='candidatemeansentiment',
            name='positive_engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatemeansentiment',
            name='positive_mean_sentiment',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
    ]
