# Generated by Django 2.2.1 on 2019-05-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'candidate-csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemeansentiment',
            options={'ordering': ['to_date_time']},
        ),
    ]
