# Generated by Django 2.2 on 2019-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_auto_20190425_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemeansentiment',
            name='num_negative_tweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatemeansentiment',
            name='num_positive_tweets',
            field=models.IntegerField(default=0),
        ),
    ]
