# Generated by Django 2.2 on 2019-04-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
                ('polarity', models.DecimalField(decimal_places=9, max_digits=10)),
                ('subjectivity', models.DecimalField(decimal_places=9, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
