# Generated by Django 2.2 on 2019-04-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
