# Generated by Django 2.2 on 2019-04-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190424_1324'),
        ('core', 'candidate-csv'),
    ]

    operations = [
    ]
