# Generated by Django 2.2 on 2019-04-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190419_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='CandidatePolarityAverage',
        ),
    ]
