# Generated by Django 2.2 on 2019-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190420_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
