# Generated by Django 2.2 on 2019-04-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190420_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
