# Generated by Django 2.2 on 2019-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tweet_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
