# Generated by Django 2.2 on 2019-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190421_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='id_str',
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweeted_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
