# Generated by Django 2.2 on 2019-04-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190421_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=100),
        ),
    ]
