# Generated by Django 2.2 on 2019-04-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190421_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
